### ISSUE TITLE
Tracking 1.0

### ISSUE THREAD

**Issue by glenjamin** [glenjamin/skin-deep#74]
Braindump of actions, will expand on these as I go.

* [ ] Document breaking API changes
* [ ] Make the breaking changes
* [ ] Fully document the new & remaining APIs
* [ ] Ensure all APIs have decent test coverage
* [ ] Extract traversal code into an internal module and test on its own
* [ ] Write a migration guide
* [ ] Publish a `beta` to npm

**Comment by burabure** [comment]
Hey,  are you still planning on releasing 1.0?, let me know If I can help with some task

**Comment by glenjamin** [comment]
Still intend to, not been doing any React component testing lately so it's slipped a bit,

Either extra test coverage, porting older tests over to the new test style or implementing the new APIs would be useful

**Comment by indexzero** [comment]
Given your time constraints if I may be so bold as to suggest a few things:

1. Implement your the remaining new APIs (`.exact`, `.any`, and `.hasClass`) in `1.1` The API documented in the `README.md` on `master` seems like it would solve most scenarios as is.
2. Publish your `beta` now so folks can use it. You can always publish another beta later on.

**Comment by glenjamin** [comment]
Yeah, implementing those is all that's really missing for a beta release.

I think I published what's here so far as a `next` tag on npm.

Its been really sunny here lately so I've not been coding as much!

**Comment by glenjamin** [comment]
I've just added `hasClass` and published `skin-deep@1.0.0-alpha1`.

Will try not to let this slip much more ☀️

**Comment by indexzero** [comment]
Awesome. Appreciate your hard work.
